---
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y doxygen
install:
  - pip install tox
script:
  - tox

deploy:
  provider: pypi
  username: __token__
  password:
    secure: GcVNEI+bewyw1HZ30KOIrHJIxdWECljDJlSlwyJq1y5uGKyNsW0MPCFFPaekfwqGYEFQ8FDm1fgbJdSEGVkTZThssBam/KV8AwgbPd6PN0TEem+NDWAXmeTpSJJIfFO+LuewQEcMiMhgDiVl1N28/1UOtCjyT6gFYBlp2B43ZlF3zAiPxplCSYN7/Ia2qsTkSxq2NfIU7Y2P+nMDrcESXmfBcQcCyDqmMZDglUBMmT8k32rUWxAYY4m7CjL3t9dYWGPmTEhpIIOz5h/I5boZQMU7vWI0IFK49sU3UEfUGhottKj2tzGMzlDkLMu5bm19bmz3h168xbXLc2SxaSie7WQwfAfXFHfGteb6fBNjyUpsCAKDDv3P9zCXNVa1NTQnKy+ddwAnPRbXA0jYxlMU1W8n+t2kWpZ0thiBJnsYxKZeLdmrHJo0XNU7sdVq82P3LWwEeONJwVAsGfUnEKnJE/jMiYKRPPdEyu0A0IVZ84pnpgPOi3NlJ0zvaR0Em2YVxdriIQPKKFLnxhfQJwsVQlJ+nqa3gnRxh1KLUG+hCTPgz1PD80+YC0YaVdTp7VnZqTQU2wOYgz9z6u6mDc6xpKAm78tXR4u4GxIPNkRQn4Lm12kVxj5VzO4y4SYh9WZY+cUx5WoDNGXnIxjKDjh/Kq9AoSCfKErtQON55AQLqNA=
  distributions: sdist bdist_wheel
  on:
    python: 3.6
    tags: true
