---
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y doxygen
install:
  - pip install tox
script:
  - tox

deploy:
  provider: pypi
  user: milliams
  password:
    secure: P98BvIsOAHKwxlGbUY/mj3ooTX+agaaOVMZvwXbPzlZYJWMYr1eKrIr1urearpCdHSmd/w1VF39bMliYUhCckZeEuNQsvpTzoesjiGcH8AF9TBumiNrpry9Z9H1PXxodlhaS3cBbdyfm+xGU88pvqqaHU7sMULJs6PXmg4YU+d4qc5EzHdUmo9ZEBbHE2e3PniJ8h5HN13fx/nXQ5gtcUvLG34zTz9fpoHUGp4+kEhjlEDwUuD5sSbiIdoADhWExAf+67WpGCjZozwkiQqnyhsylbmtkGe7XlU6K55Bj/why4eD0Sq4+eKDyPsze/1gP5oyzjhPcwFoaNSxeR1POIKkMxD2d4Z8Cd6P8nymonoOdm4rwH4yDBZc8jkEadRhUNtUIus6q9oym+oJkiunZUNd85192S9WbCQ7D1TMqTrboDJ34F49C3RPf6MuvmlG79vP5Z+KdymsjiJAY9FND7ZvWfWY1+6Ggi/VN+K23bvBh+pE2rr2Cm/LH3Y7h4OekLT2ulAgGrFwq+sD4LCRqwTWfPQwyGq7wON490BczGt4SHHTV/re4RAIgz7vR52xdQRzGAgl20joZulhoTjMqKXoGQZ3sdecfe7cVvIzhWY1ficEHV0YTl76FIY25ieLn66/3nnDuPoAnhRSjGWdBybJ0nXysW/SeGtIghBdDL7g=
  distributions: sdist bdist_wheel
  on:
    python: 3.6
    tags: true
