---
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y doxygen
install:
  - pip install tox
script:
  - tox

deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "PebYMFwWtJwd3j+1BeroBHurTmJP1oHD/XjqCOInOj49nx/R7ruFl7Ab0lGn/kQiG7FQn139kwQcBFJuEjqgGp0Iw9oxZx9SxOmxBsrnbF9Zs/73KIsMrpmddeEa12svHQFUO7v+BNUd/Uer3zQgCux7hABUkHimtPap8M43fKachR0U86SCIcVH2g9RefEltZpXXRa/L+soBIr2z9kp96HxwmNk80TAZZlqeI91/9zS6DjhyVAv0Uye4W4HV/ijSZ6pVvEF38xkFtfzSR6w6TjZha8aOu9SEEWMJVfz9jTaiWUOq+CRywlNZT7bcb3D9DFsA3m+I6FppXNDVXXvCQ9UwXEt3NF08Gr/hl4+jMfNAoxEnrLE5BCfo2G5xMP7NebOkxZ0lB4wS1Io1u+MQOXq5PgcD7j8b3yX4ZJ6eoXyHUk0kHAtuOe5h+olyXiseNqyZ70MxVBev1CT54tCaBvHh2ySKMzgTFTKD+s0a+cGSKSyAfYGVFVbrym6tgaYMKe94kme5Bmh/TW2JZ8uUFlPBNl/K0L71lsKcC53DVIVieBmVK0JhevyVt08Ooofdtu7x3e2cgtLgg/XI+pAx7l3hU+M2bREtZ/z87qV1ErF4zRgb9uoR1yjQk+wKBQSp+jVTj0VZNDwudphEAluJY2cLwUIMaYxXMDWemDEoFs="
  distributions: sdist bdist_wheel
  on:
    python: 3.6
    tags: true
